CREATE TYPE "UserRole" AS ENUM ('USER', 'ADMIN');

CREATE TABLE IF NOT EXISTS users (
	id VARCHAR(21) PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
    role "UserRole" NOT NULL DEFAULT 'USER',
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);