CREATE TABLE IF NOT EXISTS refresh_tokens (
	token VARCHAR(500) PRIMARY KEY,
	user_id VARCHAR(21) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);